Chumbok/ui-kit

src/app/componant/dentist-point/create-prescription/create-prescription.component.html, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts
=> Fix UI Design

package-lock.json, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/componant/dentist-point/create-prescription/create-prescription.component.html, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/componant/dentist-point/prescription-list/prescription-list.component.html, src/app/componant/dentist-point/prescription-list/prescription-list.component.spec.ts, src/app/componant/dentist-point/prescription-list/prescription-list.component.ts, src/app/componant/dentist-point/prescription-view/prescription-view.component.html, src/app/componant/dentist-point/prescription-view/prescription-view.component.spec.ts, src/app/componant/dentist-point/prescription-view/prescription-view.component.ts, src/app/model/create-prescription.ts, src/app/service/prescription.service.ts
Update prescription written fix code.
=> Update prescription written fix code.

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/componant/dentist-point/create-prescription/create-prescription.component.html, src/app/componant/dentist-point/prescription-list/prescription-list.component.html, src/app/layout/app-layout/template-sidenav/template-sidenav.component.html
- Add Template
- show template list
=> Add Template,show template list

src/app/componant/dentist-point/create-prescription/create-prescription.component.html
=> add calender UI

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/componant/dentist-point/create-template/create-template.component.html, src/app/componant/dentist-point/create-template/create-template.component.spec.ts, src/app/componant/dentist-point/create-template/create-template.component.ts
=> add template UI

src/app/app-routing.module.ts, src/app/componant/dentist-point/create-prescription/create-prescription.component.html, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/layout/app-layout/template-sidenav/template-sidenav.component.html, src/app/layout/app-layout/template-sidenav/template-sidenav.component.ts
=> Fixed Code For URL

src/app/app.module.ts, src/app/componant/dentist-point/create-template/create-template.component.html, src/app/componant/dentist-point/create-template/create-template.component.ts, src/app/model/create-template.ts, src/app/service/template.service.ts
=> add template backend

src/app/componant/dentist-point/create-prescription/create-prescription.component.html, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/componant/dentist-point/create-template/create-template.component.html, src/app/componant/dentist-point/create-template/create-template.component.ts, src/app/componant/dentist-point/prescription-view/prescription-view.component.html, src/app/model/create-medicine.ts, src/app/model/create-prescription.ts, src/app/model/create-template.ts, src/app/service/prescription.service.ts, src/app/service/template.service.ts
=> fixed Update work

src/app/app.module.ts, src/app/componant/dentist-point/create-appointment/create-appointment.component.html, src/app/componant/dentist-point/create-appointment/create-appointment.component.ts, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/model/create-appointment.ts, src/app/model/free-slot.ts, src/app/service/create-appointment.service.ts, src/app/service/timeslot.service.ts
almost add backend in appointment
=> almost add backend in appointment

src/app/componant/dentist-point/create-appointment/create-appointment.component.html, src/app/componant/dentist-point/create-appointment/create-appointment.component.ts, src/app/model/free-slot.ts, src/app/model/search-in-prescription-list.ts, src/app/service/timeslot.service.ts
Almost done Show free slots ui
=> Almost done Show free slot ui

src/app/componant/dentist-point/create-appointment/create-appointment.component.ts, src/app/service/timeslot.service.ts
- Show free slot search by date
=> Show free slot search by date

src/app/componant/dentist-point/create-appointment/create-appointment.component.html, src/app/componant/dentist-point/create-appointment/create-appointment.component.ts, src/app/componant/dentist-point/create-prescription/create-prescription.component.html, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/componant/dentist-point/prescription-list/prescription-list.component.html, src/app/componant/dentist-point/prescription-list/prescription-list.component.ts, src/app/service/create-appointment.service.ts, src/app/service/prescription.service.ts
- add onReload free slot
- code fixing
=> add onReload free slot view and code fixing

package-lock.json, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/componant/dentist-point/create-prescription/create-prescription.component.html, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/componant/dentist-point/edit-prescription/edit-prescription.component.html, src/app/componant/dentist-point/edit-prescription/edit-prescription.component.spec.ts, src/app/componant/dentist-point/edit-prescription/edit-prescription.component.ts, src/app/componant/dentist-point/prescription-list/prescription-list.component.html, src/app/componant/dentist-point/prescription-list/prescription-list.component.ts, src/app/componant/dentist-point/prescription-view/prescription-view.component.ts, src/app/layout/app-layout/template-sidenav/template-sidenav.component.html, src/app/service/prescription.service.ts
=> add pagination

src/app/componant/dentist-point/edit-template/edit-template.component.html
=> code fixing

package-lock.json, src/app/componant/dentist-point/edit-template/edit-template.component.html, src/app/componant/dentist-point/edit-template/edit-template.component.ts, src/app/service/template.service.ts
=> editTemplate

src/app/app-routing.module.ts, src/app/componant/dentist-point/calendar/calendar.component.ts, src/app/componant/dentist-point/create-prescription/create-prescription.component.html, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/componant/dentist-point/edit-template/edit-template.component.ts, src/app/componant/dentist-point/prescription-list/prescription-list.component.ts, src/app/service/prescription.service.ts
1. add patient profile
2. create patient 
3. pass pagination current page no
4. and fixing
=> add patient profile , create patient and fixing

package-lock.json, src/app/app-routing.module.ts, src/app/componant/dentist-point/edit-template/edit-template.component.ts, src/app/componant/dentist-point/prescription-list/prescription-list.component.html, src/app/componant/dentist-point/prescription-list/prescription-list.component.ts, src/app/componant/dentist-point/prescription-view/prescription-view.component.html, src/app/componant/dentist-point/prescription-view/prescription-view.component.ts, src/app/service/prescription.service.ts
=> PrescriptionView

src/app/componant/dentist-point/create-prescription/create-prescription.component.html, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/service/appointment-mock.service.ts, src/app/service/prescription-http.service.ts, src/app/service/prescription-mock.service.ts, src/app/service/prescription.service.ts, src/app/service/template-mock.service.ts
=> fixedWorkflashmessage

src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/componant/dentist-point/edit-template/edit-template.component.ts, src/app/service/prescription-http.service.ts, src/app/service/prescription-mock.service.ts, src/app/service/prescription.service.ts, src/app/service/template-http.service.ts, src/app/service/template-mock.service.ts, src/app/service/template.service.ts
=> Fix services

src/app/componant/dentist-point/create-prescription/create-prescription.component.html, src/app/componant/dentist-point/create-template/create-template.component.html, src/app/componant/dentist-point/create-template/create-template.component.ts, src/app/service/template-http.service.ts, src/app/service/template-mock.service.ts, src/app/service/template.service.ts
> Add multi value option in template
=> Add multi value option in template

src/app/componant/dentist-point/create-appointment/create-appointment.component.html, src/app/componant/dentist-point/create-appointment/create-appointment.component.ts, src/app/componant/dentist-point/create-prescription/create-prescription.component.html, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/componant/dentist-point/create-template/create-template.component.html, src/app/componant/dentist-point/create-template/create-template.component.ts, src/app/service/appointment-mock.service.ts, src/app/service/template-mock.service.ts
Signed-off-by: Monirozzaman Roni <eproni29@gmail.com>
- Add multi value option in create template
=> Add multi value option in create template

src/app/app-routing.module.ts, src/app/app-url.ts, src/app/componant/dentist-point/appointment-list/appointment-list.component.ts, src/app/componant/dentist-point/calendar/calendar.component.ts, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/componant/dentist-point/edit-template/edit-template.component.ts, src/app/componant/dentist-point/prescription-list/prescription-list.component.ts, src/app/componant/dentist-point/prescription-view/prescription-view.component.ts, src/app/model/create-prescription.ts, src/app/model/create-template.ts, src/app/service/prescription-mock.service.ts, src/app/service/template-mock.service.ts, src/environments/environment.ts
Add file for static url & clean some code.
=> - add static url files

src/app/app-routing.module.ts, src/app/app-url.ts, src/app/app.module.ts, src/app/componant/auth/login/login.component.ts, src/app/componant/dentist-point/auth/doctor-login/doctor-login.component.html, src/app/componant/dentist-point/auth/doctor-login/doctor-login.component.spec.ts, src/app/componant/dentist-point/auth/doctor-login/doctor-login.component.ts, src/app/componant/dentist-point/auth/doctor-logout/doctor-logout.component.html, src/app/componant/dentist-point/auth/doctor-logout/doctor-logout.component.spec.ts, src/app/componant/dentist-point/auth/doctor-logout/doctor-logout.component.ts, src/app/componant/dentist-point/auth/doctor-signup/doctor-signup.component.html, src/app/componant/dentist-point/auth/doctor-signup/doctor-signup.component.spec.ts, src/app/componant/dentist-point/auth/doctor-signup/doctor-signup.component.ts, src/app/componant/site-home/site-home.component.html, src/app/service/auth-http.service.ts, src/app/service/doctor.auth-http.service.ts, src/app/service/doctor.auth-mock.service.ts, src/app/service/doctor.auth.service.ts
=> Add doctor login

src/app/componant/dentist-point/calendar/calendar.component.ts, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/model/create-prescription.ts, src/app/service/appointment-http.service.ts, src/app/service/appointment-mock.service.ts, src/app/service/prescription-http.service.ts, src/app/service/prescription-mock.service.ts, src/app/service/prescription.service.ts, src/environments/environment.ts
=> Get api from celens

src/app/componant/dentist-point/create-prescription/create-prescription.component.html, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/componant/dentist-point/create-template/create-template.component.html, src/app/componant/dentist-point/create-template/create-template.component.ts, src/app/componant/dentist-point/edit-template/edit-template.component.html, src/app/componant/dentist-point/edit-template/edit-template.component.ts, src/app/componant/dentist-point/prescription-view/prescription-view.component.html, src/app/componant/dentist-point/prescription-view/prescription-view.component.ts, src/app/model/chief-complain.ts, src/app/model/create-medicine.ts, src/app/model/create-prescription.ts, src/app/model/create-template.ts, src/app/model/on-diagonsis.ts, src/app/model/on-examination.ts, src/app/service/prescription-http.service.ts, src/app/service/prescription-mock.service.ts, src/app/service/prescription.service.ts, src/app/service/template-http.service.ts, src/app/service/template-mock.service.ts, src/app/service/template.service.ts, src/environments/environment.ts
=> createPrescription addURl

src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/service/prescription-mock.service.ts, src/app/service/template-http.service.ts, src/app/service/template-mock.service.ts
=> createTemplate addURl

src/app/componant/dentist-point/appointment-list/appointment-list.component.html, src/app/componant/dentist-point/appointment-list/appointment-list.component.ts, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/componant/dentist-point/prescription-list/prescription-list.component.html, src/app/componant/dentist-point/prescription-list/prescription-list.component.ts, src/app/componant/dentist-point/prescription-view/prescription-view.component.html, src/app/componant/dentist-point/prescription-view/prescription-view.component.ts, src/app/service/appointment-http.service.ts, src/app/service/prescription-http.service.ts, src/app/service/prescription-mock.service.ts, src/app/service/prescription.service.ts
prescription view appointment list
=> prescription view appointment list

src/app/componant/dentist-point/create-appointment/create-appointment.component.html, src/app/componant/dentist-point/create-appointment/create-appointment.component.ts, src/app/model/create-appointment.ts, src/app/service/appointment-http.service.ts, src/app/service/appointment-mock.service.ts, src/app/service/appointment.service.ts
=> Fix Appointment UI

src/app/componant/dentist-point/auth/doctor-login/doctor-login.component.html
=> Fix patient UI

src/app/app-routing.module.ts, src/app/app-url.ts, src/app/app.module.ts, src/app/componant/dentist-point-mobiletoweb/patient-create-appointment/patient-create-appointment.component.html, src/app/componant/dentist-point-mobiletoweb/patient-create-appointment/patient-create-appointment.component.spec.ts, src/app/componant/dentist-point-mobiletoweb/patient-create-appointment/patient-create-appointment.component.ts, src/app/componant/dentist-point-mobiletoweb/patient-show-appointment/patient-show-appointment.component.html, src/app/componant/dentist-point-mobiletoweb/patient-show-appointment/patient-show-appointment.component.spec.ts, src/app/componant/dentist-point-mobiletoweb/patient-show-appointment/patient-show-appointment.component.ts, src/app/componant/dentist-point-mobiletoweb/patient-show-prescription/patient-show-prescription.component.html, src/app/componant/dentist-point-mobiletoweb/patient-show-prescription/patient-show-prescription.component.spec.ts, src/app/componant/dentist-point-mobiletoweb/patient-show-prescription/patient-show-prescription.component.ts, src/app/layout/patient-home-layout/patient-template-sidenav/patient-dashboard-sidenav.component.html
=> Add App Url

src/app/app-routing.module.ts, src/app/componant/dentist-point-mobiletoweb/patient-create-appointment/patient-create-appointment.component.html, src/app/componant/dentist-point-mobiletoweb/patient-create-appointment/patient-create-appointment.component.ts, src/app/layout/app-layout/template-sidenav/template-sidenav.component.html
=> Patient Create Appointment

src/app/app-routing.module.ts, src/app/app-url.ts, src/app/app.module.ts, src/app/componant/dentist-point-mobiletoweb/patient-create-appointment/patient-create-appointment.component.ts, src/app/componant/dentist-point-mobiletoweb/patient-show-prescription/patient-show-prescription.component.html, src/app/componant/dentist-point-mobiletoweb/patient-show-prescription/patient-show-prescription.component.ts, src/app/componant/dentist-point/auth/doctor-login/doctor-login.component.html, src/app/componant/dentist-point/auth/patient-signup/patient-signup.component.html, src/app/componant/dentist-point/auth/patient-signup/patient-signup.component.spec.ts, src/app/componant/dentist-point/auth/patient-signup/patient-signup.component.ts, src/app/componant/site-home/site-home.component.html, src/app/model/patient-create-appointment.ts, src/app/service/appointment-http.service.ts, src/app/service/patient.auth-http.service.ts, src/app/service/patient.auth-mock.service.ts, src/app/service/patient.auth.service.ts, src/app/service/prescription-http.service.ts, src/app/service/prescription-mock.service.ts, src/app/service/prescription.service.ts
=> Patient Create Prescription

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/componant/dentist-point-mobiletoweb/patient-show-appointment/patient-show-appointment.component.html, src/app/componant/dentist-point-mobiletoweb/patient-show-appointment/patient-show-appointment.component.ts, src/app/componant/dentist-point-mobiletoweb/patient-show-prescription/patient-show-prescription.component.ts, src/app/componant/dentist-point-mobiletoweb/patient-view-medicine/patient-view-medicine.component.html, src/app/componant/dentist-point-mobiletoweb/patient-view-medicine/patient-view-medicine.component.spec.ts, src/app/componant/dentist-point-mobiletoweb/patient-view-medicine/patient-view-medicine.component.ts, src/app/service/appointment-http.service.ts, src/app/service/appointment-mock.service.ts, src/app/service/appointment.service.ts, src/app/service/prescription-http.service.ts, src/app/service/prescription-mock.service.ts, src/app/service/prescription.service.ts, src/app/service/template-http.service.ts
=> Final Dentist mobile ready

package-lock.json, package.json, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/componant/dentist-point-mobiletoweb/patient-show-appointment/patient-show-appointment.component.ts, src/app/componant/dentist-point/appointment-list/appointment-list.component.ts, src/app/componant/dentist-point/auth/doctor-login/doctor-login.component.html, src/app/componant/dentist-point/auth/doctor-login/doctor-login.component.ts, src/app/componant/dentist-point/auth/doctor-signup/doctor-signup.component.ts, src/app/componant/dentist-point/create-appointment/create-appointment.component.ts, src/app/componant/dentist-point/create-prescription/create-prescription.component.ts, src/app/layout/app-layout/template-topnav/template-topnav.component.html, src/app/layout/patient-home-layout/patient-dashboard-head/patinet-dashboard-head.component.html, src/app/service/appointment-http.service.ts, src/app/service/appointment-mock.service.ts, src/app/service/appointment.service.ts
=> Confirm message

src/app/componant/dentist-point/auth/doctor-login/doctor-login.component.html, src/app/componant/dentist-point/auth/doctor-login/doctor-login.component.ts, src/app/componant/dentist-point/auth/patient-signup/patient-signup.component.html, src/app/componant/dentist-point/auth/patient-signup/patient-signup.component.ts, src/app/service/patient.auth-http.service.ts
=> Validation Check

src/app/componant/dentist-point/create-prescription/create-prescription.component.ts
=> Error fixed

src/app/componant/dentist-point/auth/patient-signup/patient-signup.component.html, src/app/componant/dentist-point/auth/patient-signup/patient-signup.component.ts
Fix Patient Registration Design
=> Fix Patient Registration Design

src/app/componant/dentist-point/auth/doctor-signup/doctor-signup.component.html, src/app/componant/dentist-point/auth/doctor-signup/doctor-signup.component.ts, src/app/componant/dentist-point/auth/patient-signup/patient-signup.component.html, src/app/componant/dentist-point/auth/patient-signup/patient-signup.component.ts
Fix Doctor Registration Design
=> Fix Doctor Registration Design

src/app/componant/dentist-point/auth/doctor-signup/doctor-signup.component.html
=> Fixing Doctor Registration Design

src/app/componant/dentist-point/auth/patient-signup/patient-signup.component.html, src/app/componant/dentist-point/auth/patient-signup/patient-signup.component.ts, src/app/componant/dentist-point/create-appointment/create-appointment.component.html, src/app/service/patient.auth-http.service.ts, src/app/service/patient.auth-mock.service.ts, src/app/service/patient.auth.service.ts
=> Fixed code

src/app/dentist-point/component/doctor/create-appointment/create-appointment.component.ts, src/app/dentist-point/service/appointment-http.service.ts
=> Fixing Date Time Formatted
